openapi: 3.1.0
info:
  title: R9S API
  version: 0.3.0
  description: Next Router Relay LLM API Documentation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: https://api.r9s.ai
  description: Production Server
security:
- api_key: []
paths:
  /v1/models:
    $ref: ./relay_openapi/r9s/paths.yaml#/paths/~1v1~1models
  /v1/models/{model}:
    $ref: ./relay_openapi/r9s/paths.yaml#/paths/~1v1~1models~1{model}
  /v1/messages:
    $ref: ./relay_openapi/anthropic/paths.yaml#/paths/~1v1~1messages
  /v1/chat/completions:
    $ref: ./relay_openapi/openai/paths.yaml#/paths/~1v1~1chat~1completions
  /v1/responses:
    $ref: ./relay_openapi/openai/paths.yaml#/paths/~1v1~1responses
  /v1/completions:
    $ref: ./relay_openapi/openai/paths.yaml#/paths/~1v1~1completions
  /v1/embeddings:
    $ref: ./relay_openapi/openai/paths.yaml#/paths/~1v1~1embeddings
  /v1/images/generations:
    $ref: ./relay_openapi/openai/paths.yaml#/paths/~1v1~1images~1generations
  /v1/images/edits:
    $ref: ./relay_openapi/openai/paths.yaml#/paths/~1v1~1images~1edits
  /v1/moderations:
    $ref: ./relay_openapi/openai/paths.yaml#/paths/~1v1~1moderations
  /v1/audio/speech:
    $ref: ./relay_openapi/openai/paths.yaml#/paths/~1v1~1audio~1speech
  /v1/audio/transcriptions:
    $ref: ./relay_openapi/openai/paths.yaml#/paths/~1v1~1audio~1transcriptions
  /v1/audio/translations:
    $ref: ./relay_openapi/openai/paths.yaml#/paths/~1v1~1audio~1translations
  /v1beta/models/{model}:generateContent:
    $ref: ./relay_openapi/gemini/paths.yaml#/paths/~1v1beta~1models~1{model}:generateContent
  /v1beta/models/{model}:streamGenerateContent:
    $ref: ./relay_openapi/gemini/paths.yaml#/paths/~1v1beta~1models~1{model}:streamGenerateContent
  /v1beta/models/{model}:embedContent:
    $ref: ./relay_openapi/gemini/paths.yaml#/paths/~1v1beta~1models~1{model}:embedContent
  /v1beta/models/{model}:batchGenerateContent:
    $ref: ./relay_openapi/gemini/paths.yaml#/paths/~1v1beta~1models~1{model}:batchGenerateContent
components:
  securitySchemes:
    api_key:
      $ref: ./relay_openapi/common/common.yaml#/components/securitySchemes/api_key
  schemas:
    GeminiBatchGenerateContentRequest:
      $ref: ./relay_openapi/gemini/schemas.yaml#/components/schemas/GeminiBatchGenerateContentRequest
    GeminiBatchGenerateContentResponse:
      $ref: ./relay_openapi/gemini/schemas.yaml#/components/schemas/GeminiBatchGenerateContentResponse
    GeminiBatch:
      $ref: ./relay_openapi/gemini/schemas.yaml#/components/schemas/GeminiBatch
