name: Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please describe the problem and the desired outcome.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What do you want to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives or workarounds you've tried?
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Links, screenshots, examples, etc.

