"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropicinputschema import AnthropicInputSchema, AnthropicInputSchemaTypedDict
from pydantic import ConfigDict
from r9s.types import BaseModel
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class AnthropicToolTypedDict(TypedDict):
    type: NotRequired[str]
    name: NotRequired[str]
    input_schema: NotRequired[AnthropicInputSchemaTypedDict]
    description: NotRequired[str]


class AnthropicTool(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )

    type: Optional[str] = None

    name: Optional[str] = None

    input_schema: Optional[AnthropicInputSchema] = None

    description: Optional[str] = None
