"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from r9s.types import BaseModel
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


AudioSpeechRequestVoice = Literal[
    "alloy",
    "ash",
    "ballad",
    "coral",
    "cedar",
    "echo",
    "fable",
    "marin",
    "onyx",
    "nova",
    "sage",
    "shimmer",
    "verse",
]
r"""Voice type"""


AudioSpeechRequestResponseFormat = Literal[
    "mp3",
    "opus",
    "aac",
    "flac",
    "wav",
    "pcm",
]


class AudioSpeechRequestTypedDict(TypedDict):
    model: str
    r"""TTS model name"""
    input: str
    r"""Text to convert to speech"""
    voice: AudioSpeechRequestVoice
    r"""Voice type"""
    instructions: NotRequired[str]
    r"""Additional instructions to control delivery style or tone. Not supported by legacy tts-1 models."""
    response_format: NotRequired[AudioSpeechRequestResponseFormat]
    r"""Audio output format (mp3, opus, aac, flac, wav, or pcm)."""
    stream_format: NotRequired[Literal["sse", "audio"]]
    r"""Streaming transport format. `sse` is not supported by legacy tts-1 models."""
    speed: NotRequired[float]
    r"""Speech speed. Valid range is 0.25 to 4.0."""


class AudioSpeechRequest(BaseModel):
    model: str
    r"""TTS model name"""

    input: str
    r"""Text to convert to speech"""

    voice: AudioSpeechRequestVoice
    r"""Voice type"""

    instructions: Optional[str] = None
    r"""Additional instructions to control delivery style or tone. Not supported by legacy tts-1 models."""

    response_format: Optional[AudioSpeechRequestResponseFormat] = "mp3"
    r"""Audio output format (mp3, opus, aac, flac, wav, or pcm)."""

    stream_format: Optional[Literal["sse", "audio"]] = None
    r"""Streaming transport format. `sse` is not supported by legacy tts-1 models."""

    speed: Optional[float] = 1
    r"""Speech speed. Valid range is 0.25 to 4.0."""
