"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from r9s.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Literal
from typing_extensions import NotRequired, TypedDict


class CompletionChoiceLogprobsTypedDict(TypedDict):
    pass


class CompletionChoiceLogprobs(BaseModel):
    pass


CompletionChoiceFinishReason = Literal[
    "stop",
    "length",
    "content_filter",
]


class CompletionChoiceTypedDict(TypedDict):
    text: str
    index: int
    finish_reason: CompletionChoiceFinishReason
    logprobs: NotRequired[Nullable[CompletionChoiceLogprobsTypedDict]]


class CompletionChoice(BaseModel):
    text: str

    index: int

    finish_reason: CompletionChoiceFinishReason

    logprobs: OptionalNullable[CompletionChoiceLogprobs] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["logprobs"]
        nullable_fields = ["logprobs"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
