"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .completionchoice import CompletionChoice, CompletionChoiceTypedDict
from .usage import Usage, UsageTypedDict
import pydantic
from pydantic.functional_validators import AfterValidator
from r9s.types import BaseModel
from r9s.utils import validate_const
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CompletionResponseTypedDict(TypedDict):
    id: str
    created: int
    model: str
    choices: List[CompletionChoiceTypedDict]
    object: Literal["completion"]
    usage: NotRequired[UsageTypedDict]


class CompletionResponse(BaseModel):
    id: str

    created: int

    model: str

    choices: List[CompletionChoice]

    OBJECT: Annotated[
        Annotated[Literal["completion"], AfterValidator(validate_const("completion"))],
        pydantic.Field(alias="object"),
    ] = "completion"

    usage: Optional[Usage] = None
