"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from r9s.types import BaseModel
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


EmbeddingRequestInputTypedDict = TypeAliasType(
    "EmbeddingRequestInputTypedDict", Union[str, List[str], List[int], List[List[int]]]
)
r"""Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays."""


EmbeddingRequestInput = TypeAliasType(
    "EmbeddingRequestInput", Union[str, List[str], List[int], List[List[int]]]
)
r"""Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays."""


EncodingFormat = Literal[
    "float",
    "base64",
]


class EmbeddingRequestTypedDict(TypedDict):
    model: str
    r"""ID of the model to use. You can use the List models API to see all of your available models."""
    input: EmbeddingRequestInputTypedDict
    r"""Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays. The input must not exceed the max input tokens for the model (8192 tokens for text-embedding-ada-002), cannot be an empty string, and any array must be 2048 dimensions or less."""
    encoding_format: NotRequired[EncodingFormat]
    r"""The format to return the embeddings in. Can be either "float" or "base64"."""
    dimensions: NotRequired[int]
    r"""The number of dimensions the resulting output embeddings should have. Only supported in text-embedding-3 and later models."""
    user: NotRequired[str]
    r"""A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse."""


class EmbeddingRequest(BaseModel):
    model: str
    r"""ID of the model to use. You can use the List models API to see all of your available models."""

    input: EmbeddingRequestInput
    r"""Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays. The input must not exceed the max input tokens for the model (8192 tokens for text-embedding-ada-002), cannot be an empty string, and any array must be 2048 dimensions or less."""

    encoding_format: Optional[EncodingFormat] = "float"
    r"""The format to return the embeddings in. Can be either "float" or "base64"."""

    dimensions: Optional[int] = None
    r"""The number of dimensions the resulting output embeddings should have. Only supported in text-embedding-3 and later models."""

    user: Optional[str] = None
    r"""A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse."""
