"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .embeddingobject import EmbeddingObject, EmbeddingObjectTypedDict
import pydantic
from pydantic.functional_validators import AfterValidator
from r9s.types import BaseModel
from r9s.utils import validate_const
from typing import List, Literal
from typing_extensions import Annotated, TypedDict


class EmbeddingUsageTypedDict(TypedDict):
    r"""The usage information for the request."""
    prompt_tokens: int
    r"""The number of tokens used by the prompt."""
    total_tokens: int
    r"""The total number of tokens used by the request."""


class EmbeddingUsage(BaseModel):
    r"""The usage information for the request."""

    prompt_tokens: int
    r"""The number of tokens used by the prompt."""

    total_tokens: int
    r"""The total number of tokens used by the request."""


class EmbeddingResponseTypedDict(TypedDict):
    data: List[EmbeddingObjectTypedDict]
    r"""The list of embeddings generated by the model."""
    model: str
    r"""The name of the model used to generate the embedding."""
    usage: EmbeddingUsageTypedDict
    r"""The usage information for the request."""
    object: Literal["list"]
    r"""The object type, which is always "list"."""


class EmbeddingResponse(BaseModel):
    data: List[EmbeddingObject]
    r"""The list of embeddings generated by the model."""

    model: str
    r"""The name of the model used to generate the embedding."""

    usage: EmbeddingUsage
    r"""The usage information for the request."""

    OBJECT: Annotated[
        Annotated[Literal["list"], AfterValidator(validate_const("list"))],
        pydantic.Field(alias="object"),
    ] = "list"
    r"""The object type, which is always "list"."""
