"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from r9s.types import BaseModel
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


EngineEmbeddingRequestInputTypedDict = TypeAliasType(
    "EngineEmbeddingRequestInputTypedDict", Union[str, List[str]]
)
r"""Input text"""


EngineEmbeddingRequestInput = TypeAliasType(
    "EngineEmbeddingRequestInput", Union[str, List[str]]
)
r"""Input text"""


EngineEmbeddingRequestEncodingFormat = Literal[
    "float",
    "base64",
]


class EngineEmbeddingRequestTypedDict(TypedDict):
    input: EngineEmbeddingRequestInputTypedDict
    r"""Input text"""
    encoding_format: NotRequired[EngineEmbeddingRequestEncodingFormat]
    dimensions: NotRequired[int]
    r"""Output dimensions"""
    user: NotRequired[str]


class EngineEmbeddingRequest(BaseModel):
    input: EngineEmbeddingRequestInput
    r"""Input text"""

    encoding_format: Optional[EngineEmbeddingRequestEncodingFormat] = "float"

    dimensions: Optional[int] = None
    r"""Output dimensions"""

    user: Optional[str] = None
