"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from r9s.types import BaseModel
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


Quality = Literal[
    "standard",
    "hd",
]


ImageGenerationRequestResponseFormat = Literal[
    "url",
    "b64_json",
]


Size = Literal[
    "256x256",
    "512x512",
    "1024x1024",
    "1792x1024",
    "1024x1792",
]


Style = Literal[
    "vivid",
    "natural",
]


class ImageGenerationRequestTypedDict(TypedDict):
    prompt: str
    r"""Image description prompt"""
    model: NotRequired[str]
    r"""Model name"""
    n: NotRequired[int]
    r"""Number of images to generate"""
    quality: NotRequired[Quality]
    response_format: NotRequired[ImageGenerationRequestResponseFormat]
    size: NotRequired[Size]
    style: NotRequired[Style]
    user: NotRequired[str]


class ImageGenerationRequest(BaseModel):
    prompt: str
    r"""Image description prompt"""

    model: Optional[str] = None
    r"""Model name"""

    n: Optional[int] = 1
    r"""Number of images to generate"""

    quality: Optional[Quality] = "standard"

    response_format: Optional[ImageGenerationRequestResponseFormat] = "url"

    size: Optional[Size] = "1024x1024"

    style: Optional[Style] = "vivid"

    user: Optional[str] = None
