"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .imageobject import ImageObject, ImageObjectTypedDict
from r9s.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ImageGenerationResponseTypedDict(TypedDict):
    created: int
    data: List[ImageObjectTypedDict]


class ImageGenerationResponse(BaseModel):
    created: int

    data: List[ImageObject]
