"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from r9s.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ModerationCategoriesTypedDict(TypedDict):
    hate: NotRequired[bool]
    hate_threatening: NotRequired[bool]
    harassment: NotRequired[bool]
    harassment_threatening: NotRequired[bool]
    self_harm: NotRequired[bool]
    self_harm_intent: NotRequired[bool]
    self_harm_instructions: NotRequired[bool]
    sexual: NotRequired[bool]
    sexual_minors: NotRequired[bool]
    violence: NotRequired[bool]
    violence_graphic: NotRequired[bool]


class ModerationCategories(BaseModel):
    hate: Optional[bool] = None

    hate_threatening: Annotated[
        Optional[bool], pydantic.Field(alias="hate/threatening")
    ] = None

    harassment: Optional[bool] = None

    harassment_threatening: Annotated[
        Optional[bool], pydantic.Field(alias="harassment/threatening")
    ] = None

    self_harm: Annotated[Optional[bool], pydantic.Field(alias="self-harm")] = None

    self_harm_intent: Annotated[
        Optional[bool], pydantic.Field(alias="self-harm/intent")
    ] = None

    self_harm_instructions: Annotated[
        Optional[bool], pydantic.Field(alias="self-harm/instructions")
    ] = None

    sexual: Optional[bool] = None

    sexual_minors: Annotated[Optional[bool], pydantic.Field(alias="sexual/minors")] = (
        None
    )

    violence: Optional[bool] = None

    violence_graphic: Annotated[
        Optional[bool], pydantic.Field(alias="violence/graphic")
    ] = None
