"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from r9s.types import BaseModel
from r9s.utils import validate_const
from typing import List, Literal, Optional
from typing_extensions import Annotated, TypedDict


class ModelTypedDict(TypedDict):
    id: str
    r"""Model identifier"""
    created: int
    r"""Creation timestamp"""
    owned_by: str
    r"""Model owner"""
    object: Literal["model"]
    modality: str
    r"""Expanded modality description, for example text+image->text"""
    context_length: int
    r"""Expanded context length in tokens"""
    channels: List[str]
    r"""Expanded channel names"""
    endpoints: List[str]
    r"""Expanded endpoint paths"""


class Model(BaseModel):
    id: str
    r"""Model identifier"""

    created: int
    r"""Creation timestamp"""

    owned_by: str
    r"""Model owner"""

    modality: Optional[str] = None
    r"""Expanded modality description, for example text+image->text"""

    context_length: Optional[int] = None
    r"""Expanded context length in tokens"""

    channels: Optional[List[str]] = None
    r"""Expanded channel names"""

    endpoints: Optional[List[str]] = None
    r"""Expanded endpoint paths"""

    OBJECT: Annotated[
        Annotated[Literal["model"], AfterValidator(validate_const("model"))],
        pydantic.Field(alias="object"),
    ] = "model"
