"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsetool import ResponseTool, ResponseToolTypedDict
from .toolchoice import ToolChoice, ToolChoiceTypedDict
import pydantic
from r9s.types import BaseModel
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


ResponseInputItemTypedDict = Dict[str, Any]
r"""A native Responses API input item accepted as a pass-through dictionary."""


ResponseInputItem = Dict[str, Any]
r"""A native Responses API input item accepted as a pass-through dictionary."""


InputTypedDict = TypeAliasType(
    "InputTypedDict", Union[str, List[ResponseInputItemTypedDict]]
)
r"""Input content for the Responses API. Can be a plain string or an array of native input items."""


Input = TypeAliasType("Input", Union[str, List[ResponseInputItem]])
r"""Input content for the Responses API. Can be a plain string or an array of native input items."""


ResponseRequestModalities = Literal[
    "text",
    "audio",
]


ResponseRequest1 = Literal[
    "none",
    "auto",
    "required",
]


ResponseRequestToolChoiceTypedDict = TypeAliasType(
    "ResponseRequestToolChoiceTypedDict", Union[ToolChoiceTypedDict, ResponseRequest1]
)
r"""Tool selection strategy"""


ResponseRequestToolChoice = TypeAliasType(
    "ResponseRequestToolChoice", Union[ToolChoice, ResponseRequest1]
)
r"""Tool selection strategy"""


ResponseRequestType = Literal[
    "text",
    "json_object",
    "json_schema",
]
r"""The type of response format"""


class ResponseRequestFormatTypedDict(TypedDict):
    r"""An object specifying the format that the model must output. Setting to { \"type\": \"json_schema\", \"name\": \"...\", \"schema\": {...} } enables Structured Outputs which ensures the model will match your supplied JSON schema.
    Setting to { \"type\": \"json_object\" } enables JSON mode, which ensures the model generates valid JSON.

    """

    type: NotRequired[ResponseRequestType]
    r"""The type of response format"""
    name: NotRequired[str]
    r"""Name for the schema (required when type is json_schema)"""
    schema_: NotRequired[Dict[str, Any]]
    r"""JSON schema definition for structured outputs"""
    strict: NotRequired[bool]
    r"""Whether to enforce strict schema matching"""


class ResponseRequestFormat(BaseModel):
    r"""An object specifying the format that the model must output. Setting to { \"type\": \"json_schema\", \"name\": \"...\", \"schema\": {...} } enables Structured Outputs which ensures the model will match your supplied JSON schema.
    Setting to { \"type\": \"json_object\" } enables JSON mode, which ensures the model generates valid JSON.

    """

    type: Optional[ResponseRequestType] = None
    r"""The type of response format"""

    name: Optional[str] = None
    r"""Name for the schema (required when type is json_schema)"""

    schema_: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="schema")] = None
    r"""JSON schema definition for structured outputs"""

    strict: Optional[bool] = None
    r"""Whether to enforce strict schema matching"""


Verbosity = Literal[
    "low",
    "medium",
    "high",
]
r"""Verbosity level for the text output"""


class TextTypedDict(TypedDict):
    r"""Text output configuration"""

    format_: NotRequired[ResponseRequestFormatTypedDict]
    r"""An object specifying the format that the model must output. Setting to { \"type\": \"json_schema\", \"name\": \"...\", \"schema\": {...} } enables Structured Outputs which ensures the model will match your supplied JSON schema.
    Setting to { \"type\": \"json_object\" } enables JSON mode, which ensures the model generates valid JSON.

    """
    verbosity: NotRequired[Verbosity]
    r"""Verbosity level for the text output"""


class Text(BaseModel):
    r"""Text output configuration"""

    format_: Annotated[
        Optional[ResponseRequestFormat], pydantic.Field(alias="format")
    ] = None
    r"""An object specifying the format that the model must output. Setting to { \"type\": \"json_schema\", \"name\": \"...\", \"schema\": {...} } enables Structured Outputs which ensures the model will match your supplied JSON schema.
    Setting to { \"type\": \"json_object\" } enables JSON mode, which ensures the model generates valid JSON.

    """

    verbosity: Optional[Verbosity] = None
    r"""Verbosity level for the text output"""


Effort = Literal[
    "none",
    "minimal",
    "low",
    "medium",
    "high",
    "xhigh",
]
r"""The effort level for reasoning (none/minimal=fast, low/medium=balanced, high/xhigh=thorough)"""


class ReasoningTypedDict(TypedDict):
    r"""Configuration for reasoning models (e.g., o1, o3, gpt-5). Controls how the model uses reasoning tokens to \"think\" through the problem."""

    effort: NotRequired[Effort]
    r"""The effort level for reasoning (none/minimal=fast, low/medium=balanced, high/xhigh=thorough)"""
    summary: NotRequired[str]
    r"""Reasoning summary level or summary payload"""
    generate_summary: NotRequired[str]
    r"""Deprecated alias for reasoning summary level. Kept for compatibility with official docs."""


class Reasoning(BaseModel):
    r"""Configuration for reasoning models (e.g., o1, o3, gpt-5). Controls how the model uses reasoning tokens to \"think\" through the problem."""

    effort: Optional[Effort] = None
    r"""The effort level for reasoning (none/minimal=fast, low/medium=balanced, high/xhigh=thorough)"""

    summary: Optional[str] = None
    r"""Reasoning summary level or summary payload"""

    generate_summary: Optional[str] = None
    r"""Deprecated alias for reasoning summary level. Kept for compatibility with official docs."""


Truncation = Literal[
    "auto",
    "disabled",
]
r"""The truncation strategy to use for the model response.
- auto: If input exceeds context window, truncate by dropping items from beginning
- disabled: Request fails with 400 error if input exceeds context window (default)

"""


ResponseRequestStopTypedDict = TypeAliasType(
    "ResponseRequestStopTypedDict", Union[str, List[str]]
)
r"""Up to 4 sequences where the API will stop generating further tokens"""


ResponseRequestStop = TypeAliasType("ResponseRequestStop", Union[str, List[str]])
r"""Up to 4 sequences where the API will stop generating further tokens"""


class ConversationTypedDict(TypedDict):
    id: str
    r"""The unique ID of the conversation."""


class Conversation(BaseModel):
    id: str
    r"""The unique ID of the conversation."""


ConversationRefTypedDict = TypeAliasType(
    "ConversationRefTypedDict", Union[str, ConversationTypedDict]
)
r"""Conversation reference for the Responses API."""


ConversationRef = TypeAliasType("ConversationRef", Union[str, Conversation])
r"""Conversation reference for the Responses API."""


class PromptTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the prompt template to use."""
    variables: NotRequired[Dict[str, Any]]
    r"""Optional variables to substitute into the prompt template."""
    version: NotRequired[str]
    r"""Optional version of the prompt template to use."""


class Prompt(BaseModel):
    id: str
    r"""The unique identifier of the prompt template to use."""

    variables: Optional[Dict[str, Any]] = None
    r"""Optional variables to substitute into the prompt template."""

    version: Optional[str] = None
    r"""Optional version of the prompt template to use."""


IncludeItem = Literal[
    "web_search_call.action.sources",
    "code_interpreter_call.outputs",
    "computer_call_output.output.image_url",
    "file_search_call.results",
    "message.input_image.image_url",
]
r"""Additional response data to include."""


ResponseRequestServiceTier = Literal[
    "auto",
    "default",
    "flex",
    "scale",
    "priority",
]
r"""Processing tier for serving the request."""


class ResponseRequestTypedDict(TypedDict):
    model: str
    r"""Model name"""
    input: InputTypedDict
    r"""Input content for the Responses API. Can be a plain string or an array of native input items."""
    instructions: NotRequired[str]
    r"""System-level instructions to guide model behavior and response style (similar to system message)"""
    temperature: NotRequired[float]
    r"""Controls output randomness, higher values mean more random"""
    top_p: NotRequired[float]
    r"""Nucleus sampling parameter, controls output diversity"""
    max_output_tokens: NotRequired[int]
    r"""Maximum number of tokens to generate"""
    max_tool_calls: NotRequired[int]
    r"""Maximum number of total built-in tool calls that can be processed in the response."""
    stream: NotRequired[bool]
    r"""Whether to enable streaming"""
    include: NotRequired[List[IncludeItem]]
    r"""Additional response data to include in the response."""
    conversation: NotRequired[ConversationRefTypedDict]
    r"""Conversation reference for stateful Responses API usage."""
    modalities: NotRequired[List[ResponseRequestModalities]]
    r"""Response modality types"""
    tools: NotRequired[List[ResponseToolTypedDict]]
    r"""Available tools list (using flat format)"""
    tool_choice: NotRequired[ResponseRequestToolChoiceTypedDict]
    r"""Tool selection strategy"""
    parallel_tool_calls: NotRequired[bool]
    r"""Whether to enable parallel function calling during tool use. When false, ensures exactly zero or one tool is called."""
    text: NotRequired[TextTypedDict]
    r"""Text output configuration"""
    previous_response_id: NotRequired[str]
    r"""The ID of a previous response to continue the conversation from. Cannot be used together with conversation."""
    prompt: NotRequired[PromptTypedDict]
    r"""Reference to a prompt template and its variables."""
    prompt_cache_key: NotRequired[str]
    r"""Cache key used for prompt caching."""
    prompt_cache_retention: NotRequired[str]
    r"""Prompt cache retention policy."""
    safety_identifier: NotRequired[str]
    r"""Stable user safety identifier recommended by OpenAI for policy enforcement and abuse detection."""
    service_tier: NotRequired[ResponseRequestServiceTier]
    r"""Processing tier used to serve the request."""
    store: NotRequired[bool]
    r"""Whether to store the generated model response for later retrieval via API.
    Defaults to true. Set to false to disable storage (required for ZDR organizations).

    """
    background: NotRequired[bool]
    r"""Whether to run the model response in the background asynchronously. Useful for long-running tasks."""
    reasoning: NotRequired[ReasoningTypedDict]
    r"""Configuration for reasoning models (e.g., o1, o3, gpt-5). Controls how the model uses reasoning tokens to \"think\" through the problem."""
    truncation: NotRequired[Truncation]
    r"""The truncation strategy to use for the model response.
    - auto: If input exceeds context window, truncate by dropping items from beginning
    - disabled: Request fails with 400 error if input exceeds context window (default)

    """
    stop: NotRequired[ResponseRequestStopTypedDict]
    r"""Up to 4 sequences where the API will stop generating further tokens"""
    metadata: NotRequired[Dict[str, Any]]
    r"""Additional metadata for tracking and organization purposes"""
    user: NotRequired[str]
    r"""Legacy user identifier. Prefer safety_identifier for new integrations."""


class ResponseRequest(BaseModel):
    model: str
    r"""Model name"""

    input: Input
    r"""Input content for the Responses API. Can be a plain string or an array of native input items."""

    instructions: Optional[str] = None
    r"""System-level instructions to guide model behavior and response style (similar to system message)"""

    temperature: Optional[float] = None
    r"""Controls output randomness, higher values mean more random"""

    top_p: Optional[float] = None
    r"""Nucleus sampling parameter, controls output diversity"""

    max_output_tokens: Optional[int] = None
    r"""Maximum number of tokens to generate"""

    max_tool_calls: Optional[int] = None
    r"""Maximum number of total built-in tool calls that can be processed in the response."""

    stream: Optional[bool] = False
    r"""Whether to enable streaming"""

    include: Optional[List[IncludeItem]] = None
    r"""Additional response data to include in the response."""

    conversation: Optional[ConversationRef] = None
    r"""Conversation reference for stateful Responses API usage."""

    modalities: Optional[List[ResponseRequestModalities]] = None
    r"""Response modality types"""

    tools: Optional[List[ResponseTool]] = None
    r"""Available tools list (using flat format)"""

    tool_choice: Optional[ResponseRequestToolChoice] = None
    r"""Tool selection strategy"""

    parallel_tool_calls: Optional[bool] = True
    r"""Whether to enable parallel function calling during tool use. When false, ensures exactly zero or one tool is called."""

    text: Optional[Text] = None
    r"""Text output configuration"""

    previous_response_id: Optional[str] = None
    r"""The ID of a previous response to continue the conversation from. Cannot be used together with conversation."""

    prompt: Optional[Prompt] = None
    r"""Reference to a prompt template and its variables."""

    prompt_cache_key: Optional[str] = None
    r"""Cache key used for prompt caching."""

    prompt_cache_retention: Optional[str] = None
    r"""Prompt cache retention policy."""

    safety_identifier: Optional[str] = None
    r"""Stable user safety identifier recommended by OpenAI for policy enforcement and abuse detection."""

    service_tier: Optional[ResponseRequestServiceTier] = None
    r"""Processing tier used to serve the request."""

    store: Optional[bool] = True
    r"""Whether to store the generated model response for later retrieval via API.
    Defaults to true. Set to false to disable storage (required for ZDR organizations).

    """

    background: Optional[bool] = False
    r"""Whether to run the model response in the background asynchronously. Useful for long-running tasks."""

    reasoning: Optional[Reasoning] = None
    r"""Configuration for reasoning models (e.g., o1, o3, gpt-5). Controls how the model uses reasoning tokens to \"think\" through the problem."""

    truncation: Optional[Truncation] = "disabled"
    r"""The truncation strategy to use for the model response.
    - auto: If input exceeds context window, truncate by dropping items from beginning
    - disabled: Request fails with 400 error if input exceeds context window (default)

    """

    stop: Optional[ResponseRequestStop] = None
    r"""Up to 4 sequences where the API will stop generating further tokens"""

    metadata: Optional[Dict[str, Any]] = None
    r"""Additional metadata for tracking and organization purposes"""

    user: Optional[str] = None
    r"""Legacy user identifier. Prefer safety_identifier for new integrations."""
