"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from r9s.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class StreamOptionsTypedDict(TypedDict):
    include_usage: NotRequired[bool]
    r"""Whether to include usage statistics"""


class StreamOptions(BaseModel):
    include_usage: Optional[bool] = None
    r"""Whether to include usage statistics"""
